FEW_SHOT_TEMPLATES = [
    """
    00:00:05:520 - 00:00:16:960:  kính chào quý vị rất hân hạnh được gặp lại quý vị trong chương trình sáu mươi giây của đài truyền hình thành phố hồ chí minh chương trình sáng nay thứ ba ngày ba mươi mốt tháng mười sẽ chuyển đến quý vị những nội dung đáng chú ý sau đây


    00:00:18:400 - 00:00:35:040:  các tỉnh miền trung chủ động ứng phó với mưa lũ giảm thiểu thiệt hại về người và của tỉnh bến tre công bố tình huống khẩn cấp sạt lở xâm thực bờ biển ở huyện ba tri sập giàn giáo công trường đang xây dựng ở ham buốt của đức ít nhất ba công nhân thiệt mạng
    00:00:35:920 - 00:00:55:120:  thưa quý vị hai ngày qua các tỉnh miền trung có mưa lớn có nơi trên bốn trăm mi li mét gây ngập lụt ở các khu dân cư vùng trũng thấp mưa lũ cũng khiến giao thông bị ách tắc ở một số tuyến đường tây tỉnh hà tĩnh hai phụ nữ và một trẻ em ở huyện hương khê đang đi trên đường ngập thì sẩy chân vào vũng sâu bị nước cuốn mất tích
    00:00:55:920 - 00:02:04:480:  khoảng mười giờ ngày ba mươi tháng mười chị tống thị trang ba mươi ba tuổi và chị nguyễn thị hoa ba mươi mốt tuổi trú xã hà linh huyện hương khê đi làm ở trại gà trên đường về nhà thì bị nước lũ cuốn mất tích đến cuối giờ chiều thi thể chị trang được tìm thấy đến tối qua hàng chục người vẫn đang tìm kiếm chị hoa còn tại xã hương thủy lúc mười lăm giờ ba mươi phút cùng ngày em nguyễn văn dũng mười ba tuổi đi bộ trên đường ngập nước gần nửa mét thì bị sẩy chân vào vũng nước sâu và bị nhấn chìm đến hơn hai mươi giờ ba mươi phút thi thể nạn nhân được tìm thấy tại huyện căng lộc chính quyền cũng kịp thời dùng xuồng mái tiếp cận giải cứu chính công nhân đang thi công cao tốc bị nước lũ cô lập giữa lán trại gần sông già đoạn qua xã sơn lộc trước đó do mưa nhỏ nên những người này chủ quan sau đó nước dân nhanh không kịp rời đi trong đợt mưa lớn lần này ảnh hưởng nặng nhất là hà tĩnh gần năm trăm nhà dân bị ngập cao hơn nửa mét đường hồ chí minh quốc lộ mười lăm ngập từ ba mươi đến bảy mươi xăng ti mét đường sắt bắc nam gián đoạn vì sạt lở hơn bốn nghìn năm trăm học sinh phải nghỉ học dự báo mưa ở hà tĩnh còn kéo dài tới ngày hai tháng mười một
    00:02:05:200 - 00:02:37:520:  trước diễn biến phức tạp của tình hình mưa lũ ban chỉ đạo quốc gia về phòng chống thiên tai yêu cầu các tỉnh từ nghệ an đến quảng ngãi theo dõi chặt chẽ dự báo thời tiết cảnh báo về mưa lớn ngập lụt lũ quét sạt lở đất thông tin kịp thời đến các cấp chính quyền người dân biết để chủ động phòng tránh mưa lũ tại hà tĩnh đã làm nhiều điểm bị sạt lở và đất đá tràn lên đường ray tuyến đường sắt bắc nam bị chia cắt và bắt buộc phải cấm chạy tàu qua vào rạng sáng ngày ba mươi tháng mười ngay sau khi sự cố xảy ra các đơn vị đã nhanh chóng giải tỏa hành khách tập trung mọi nguồn lực để khắc phục sự cố


    00:02:37:920 - 00:03:08:160:  hai chuyến tàu ét xê một từ hà nội dào do ét xê hai mươi từ đà nẵng ra phải dừng hoạt động như khoảng gần bốn trăm hành khách ông trần anh tuấn phó tổng giám đốc tổng công ty đường sắt việt nam cho biết toàn bộ hành khách đã được kiểm lại bằng giao ô bố ờ chuyển qua tàu để di chuyển tiếp theo lịch trình mạng đồng thời tổng công ty thì cũng đã chỉ đạo các đơn vị chăm sóc đầy đủ về lương thực phẩm ý kiến của chúng tôi là trong đêm nay thì sẽ không tiến cho từng tàu này qua hai triệu nội hà nội
    00:03:08:320 - 00:03:45:360:  ngày ba mươi tháng mười chính quyền tỉnh bến tre đã công bố tình huống khẩn cấp sạt lở xâm thực bờ biển ngân huyện ba tri khẩn trương triển khai các biện pháp ứng phó khu vực bị sạt lở xâm thực nghiêm trọng thuộc địa bàn xã bảo thuận chiều dài khoảng bốn phẩy bảy ki lô mét làm ảnh hưởng trực tiếp đến một trăm mười lăm hộ dân làm hư hại mười lăm căn nhà sạt lở cũng làm hư hỏng hoàn toàn một trăm mét đường bê tông sáu trăm năm mươi mét bờ bao diện tích đất bị ảnh hưởng khoảng năm trăm ba mươi lăm héc ta trên đất tường phòng hộ ven biển mất mười sáu héc ta các cơ quan chức năng đang triển khai các biện pháp khẩn cấp để ứng phó và khắc phục hậu quả sơ tán cân cấp người và tài sản ra khỏi khu vực sạt lở nguy hiểm
    00:03:48:560 - 00:04:13:360:  thưa quý vị hàng năm khi nước lũ tràn về người dân đồng bằng sông cửu long lại nhộn nhịp thu hoạch sản vật mùa nước nổi đây cũng là thời điểm các địa phương trong huyện phụng hiệp tỉnh hậu giang tổ chức hội thi đẩy côn bắt cá mùa nước nổi qua đó duy trì và bảo tồn ngành nghề đánh bắt cũng như tuyên truyền nâng cao ý thức cho người dân trong việc khai thác nguồn lệ thủy sản đúng quy định


    00:04:14:000 - 00:05:15:280:  gần hai mươi năm làm nghề đẩy cô bắt cá năm nay ông huỳnh chí khải được chọn làm đại diện tham gia tranh tài tới cái mùa nước nổi á là ai cũng dẫn gà gỗ tím cá hết á thấy nó hấp dẫn lắm côn là dụng cụ được làm bằng những cọng sắt nhỏ mang vào hai đoạn tre dài trước bụi ghe khi người đẩy côn chơi ghe lau về phía trước thanh cô sắt chạm cá chuối tạo thành một vùng bong nước lúc đó chỉ việc lội xuống dùng n nôm bắt cá hôn kéo côn rồi đó nó cũng có ý nghĩa chỗ ấp vùng như kết hợp với sở ủy ban xã và mỹ để triển khai cái mô hình này kéo côn này nó mới gọi là cá lớn thì cái nguồn cá nhỏ thì nó được bảo đảm năm nay thì huyện muốn là nâng lên cái quy mô cấp huyện đó là tất cả mười lăm xã thị trấn trên địa bàn đều có tham gia là quảng bá về hình ảnh đất và người vô nghiệp thời gian tới huyện phụng hiệp sẽ phát triển mô hình thành một hình thức du lịch trải nghiệm cho du khách tham quan khám phá hình thức đánh bắt truyền thống mùa đất nổi này
    00:05:18:240 - 00:05:39:680:  những tập tiếp theo của bộ phim dâu bể mùa xưa đã đi vào giai đoạn cao trào ở tập mười một chuyện tình tay ba giữa hai anh em hiếu và nghĩa có bước ngoặt mới bông và hiếu dần mở lòng cho nhau cơ hội phát triển tình cảm riêng nghĩa vẫn ôm mối tương tư trong lòng khiến bậc làm cha như ông bá đau lòng
    00:05:39:760 - 00:05:52:720:  một vụ hành hung bất ngờ diễn ra ở tiệm đèn kéo quân của nghĩa ông bá và nghĩa lo lắng cầu cứu trong khi đó bệnh tình của hiếu có những chuyển biến xấu bà bá tiếp tục bên trọng bên kinh với hai anh em hiếu nghĩa
    00:05:53:360 - 00:06:04:480:  mời quý vị đón xem những tình tiết hấp dẫn trong tập mười một phim dâu bể mùa xưa phát sóng lúc mười chín giờ ba mươi hôm nay ba mươi mốt tháng mười trên kênh hát tê vê bảy
    00:06:06:320 - 00:06:15:440:  góp phần an ninh trật tự lên cơn tâm thần nam thanh niên dùng r rợ truy sát ba người trong gia đình
    00:06:16:560 - 00:06:24:000:  lực lượng chức năng thu giữ gần một phẩy năm tấn thực phẩm đông lạnh hết hạn sử dụng bốc mùi ôi thiu
    00:06:25:840 - 00:06:46:560:  chương trình tiếp tục với các thông tin an ninh trật tự trong lúc lên cơn tâm thần nam thanh niên ở tỉnh bình định dùng rựa truy sát ba người trong gia đình khiến cha và anh ruột tử vong còn mẹ bị thương rất nặng chiều ba mươi tháng mười công an tỉnh bình định cho biết đang tạm giữ hình sự đối tượng hồ thanh cường ba mươi bốn tuổi để điều tra về hành vi giết người
    00:06:46:800 - 00:07:12:000:  khoảng chín giờ ba mươi phút sáng ngày ba mươi tháng mười cường bất ngờ dùng dao chém vào cha mẹ ruột và anh ruột hậu quả người cha tới dông tại chỗ anh trai đưa đi cấp cứu tại trung tâm y tế thị xã an nhơn nhưng tử vong trên đường đi còn người mẹ bị thương rất nặng khi đang được cấp cứu tại bệnh viện đa khoa tỉnh bình định theo lãnh đạo ủy ban nhân dân thị xã an nhơn cường là người bị tâm thần phân liệt đang điều trị bởi tâm thần ngoại trú
    00:07:12:640 - 00:07:22:400:  công an thành phố tây ninh cho biết đang tạm giữ hình sự ba đối tượng để điều tra về hành vi trộm cắp tài sản và tiêu thụ tài sản do người khác phạm tội mà có
    00:07:22:800 - 00:08:00:320:  đó là huỳnh thanh son sinh năm một nghìn chín trăm chín mươi ba và nguyễn trung hậu sinh năm hai ngàn lẻ một cùng ngụ xã chà là và đỗ thế kiệt sinh năm một ngàn chín trăm tám mươi tư ngụ xã cầu khởi huyện dương minh châu hôm hai mươi chín tháng mười công an nhận tin báo của người dân về việc vườn mai bị bốn tên trộm cắt khóa cổng rào đột nhập lấy trộm một cây mai vàng lớn có giá trị một trăm năm mươi triệu đồng lực lượng công an phối hợp truy bắt được son và hậu các đối tượng khai nhận son bà hậu cùng hai đối tượng khác đột nhập nhà anh ét trộm mai bán được mười bốn triệu đồng rồi chia nhau tiêu xài công an thành phố tây ninh đang làm rõ vụ việc và truy bắt các đối tượng còn lại
    00:08:00:880 - 00:08:10:560:  ngày ba mươi tháng mười công an tỉnh quảng nam cho biết vừa phát hiện và bắt quả tang một ô tô khách mười sáu chỗ vận chuyển gần năm ngàn viên pháo lậu
    00:08:11:120 - 00:08:39:280:  lúc hai mươi ba giờ ngày hai mươi chín tháng mười tại thị trấn thành mỹ huyện nam giang lực lượng chức năng cho dừng xe ô tô khách mười sáu chỗ đang lưu thông theo hướng kon tum đi đà nẵng qua kiểm tra phát hiện trên xe chở ba thùng xốp bên trong có chín mươi sáu hộp pháo tổng cộng bốn nghìn bảy trăm lẻ bốn viên tại thời điểm kiểm tra tài xế không xuất trình được giấy tờ chứng minh nguồn gốc số pháo trên lực lượng chức năng đã lập biên bản bàn giao vụ việc cho công an huyện nam giang để tiếp tục điều tra xử lý
    00:08:39:600 - 00:08:47:920:  gần một phẩy năm tấn thực phẩm đông lạnh hết hạn sử dụng bốc mùi ôi thiêu vừa bị lực lượng chức năng tỉnh bắc kạn phát hiện và thu giữ
    00:08:48:320 - 00:09:23:040:  ngày ba mươi tháng mười kiểm tra một kho hàng đông lạnh trên phường sông cầu lực lượng chức năng phát hiện nhiều sản phẩm đã hết thời hạn sử dụng biến màu ôi thiu bốc mùi hôi có trọng lượng gần một phẩy năm tấn đó là các loại cá thịt ba chỉ rút xương sườn heo chân giò heo gà nguyên con thịt trâu chân gà nêm chua xúc xích đông lạnh tại thời điểm kiểm tra chủ kho hàng đông lạnh là ông phạm đức của sinh năm một nghìn chín trăm tám mươi mốt không xuất trình được các giấy tờ chứng minh nguồn gốc xuất xứ của các sản phẩm tổ công tác đã lập biên bản và đang phối hợp xác minh để xử lý theo quy định của pháp luật
    00:09:23:440 - 00:09:30:960:  trong phần tin thế giới hấp dẫn cuộc thi vô địch thế giới phô mai rắc cờ lét tại thụyỵ sĩ
    00:09:32:240 - 00:09:39:600:  phiên bản trung quốc của vợ ba lê thăng gu nha thơ đức ba kết hợp nét đẹp của ba lê phương đông
    00:09:41:760 - 00:09:56:240:  thưa quý vị ngày ba mươi tháng mười một vụ sập giàn giáo đã xảy ra tại một công trường xây dựng ở thành phố ham buốt miền bắc nước đức làm ít nhất ba công nhân thiệt mạng và nhiều người khác bị chôn vùi dưới đống đổ nát
    00:09:56:640 - 00:10:31:600:  theo lực lượng cứu hỏa địa phương vào thời điểm xảy ra vụ tai nạn có khoảng một ngàn ba trăm đến một ngàn năm trăm công nhân đang làm việc tại công trường dàn giáo cao hơn mặt đất khoảng tám tầng trước khi đổ sập công trường xây dựng đã được sơ tán sau vụ tai nạn lực lượng cứu hỏa cho biết nỗ lực cứu hộ gặp nhiều khó khăn nhà chức trách ban đầu cho biết có năm người thiệt mạng nhưng sau đó họ báo cáo lại là ba người vụ tai nạn xảy ra tại khu dân cư ở quận ha phen si ti thuộc thành phố cảng ham buốt trên sông an bơ nơi đang được tái phát triển với nhiều tòa nhà chung cư văn phòng khách sạn và cửa hàng
    00:10:32:160 - 00:10:57:680:  thưa quý vị cuộc xung đột giữa lực lượng hamas mát tên kiểm soát dải ga da và ít israel ren đã có những diễn biến leo thang khi quân đội israel ren mở rộng chiến dịch trên bộ tại ga da trước đó hôm bảy tháng mười ha mát đã bất ngờ đột kích tấn công vào các hệ thành phố thị trấn của israel giết chết nhiều người và bắt giữ các con tin có hai con trai bị hamas mát bắt cóc một bà mẹ sờra en mới đây đã là một đạo phim hoạt hình để kể về câu chuyện đau buồn của mình
    00:10:58:240 - 00:11:28:160:  đây là câu chuyện về da gin mười hai tuổi và o mười sáu tuổi bị bắt cóc tại khu vực ni ô di miền nam i israel khi chúng ở nhà một mình mẹ của hai đứa trẻ là người kể chuyện trong đoạn phim hoạt hình đạo diễn hoạt hình du ni gút man đã thực hiện đoạn phim ông là người nổi tiếng tại israel với bộ phim mang tên quaýt ba siia kể về chiến tranh li bang năm một ngàn chín trăm tám mươi hai gút man đã trò chuyện với ren nan gom để lắng nghe câu chuyện của cô sau đó thực hiện đoạn phim
    00:11:28:560 - 00:11:44:640:  tôi đã liên tục gặp ác mộng khi thức dậy tôi tự nhủ với chính mình rằng phải đưa cơn ác mộng này ra khỏi đầu trẻ em không phải là con bài mặc cả trẻ em ở bất kỳ nơi nào trên thế giới lẽ ra không nên bị liên lụy dù tại ga da israel hay tại u cờ rai na
    00:11:44:720 - 00:12:02:800:  phim kết thúc có hậu gồm đoàn tụ với những người con và đây cũng chính là điều mà bà đang hy vọng hai con tin lớn tuổi người israel được ha mát thả tự do nói với bà g gôn rằng họ đã nghe thấy tiếng trẻ con khi bị bắt giữ ở ga gaza điều này khiến g tin rằng con của mình vẫn còn sống


    Kết quả trả về
    ```json
    [
        {
            "eve": "Mưa lũ tại miền Trung và thiệt hại về người",
            "sum": "Mưa lũ lớn tại miền Trung Việt Nam đã gây ngập lụt, ách tắc giao thông và dẫn đến nhiều trường hợp mất tích, tử vong, thiệt hại nặng nề nhất tại Hà Tĩnh.",
            "ts": ["00:00:18:400", "00:02:04:480"],
            "cnt": "Các tỉnh miền Trung đang chủ động ứng phó với mưa lũ để giảm thiểu thiệt hại về người và của. Miền Trung trong hai ngày qua đã có mưa lớn, có nơi trên 400 milimét, gây ngập lụt ở các khu dân cư vùng trũng thấp và ách tắc giao thông ở một số tuyến đường. Tại tỉnh Hà Tĩnh, hai phụ nữ và một trẻ em ở huyện Hương Khê đã bị nước cuốn mất tích khi đang đi trên đường ngập. Cụ thể, khoảng 10 giờ ngày 30 tháng 10, chị Tống Thị Trang (33 tuổi) và chị Nguyễn Thị Hoa (31 tuổi) trú xã Hà Linh, huyện Hương Khê, đã bị nước lũ cuốn trôi khi trên đường về nhà. Thi thể chị Trang đã được tìm thấy vào cuối giờ chiều cùng ngày, còn việc tìm kiếm chị Hoa vẫn tiếp diễn. Tại xã Hương Thủy, lúc 15 giờ 30 phút cùng ngày, em Nguyễn Văn Dũng (13 tuổi) đã bị sẩy chân vào vũng nước sâu và bị nhấn chìm khi đi bộ trên đường ngập nước. Đến hơn 20 giờ 30 phút, thi thể nạn nhân đã được tìm thấy. Ngoài ra, tại huyện Can Lộc, chín công nhân thi công cao tốc đã bị nước lũ cô lập giữa lán trại gần sông Già, xã Sơn Lộc. Đợt mưa lớn này đã ảnh hưởng nặng nhất đến Hà Tĩnh, với gần 500 nhà dân bị ngập sâu hơn nửa mét, đường Hồ Chí Minh và Quốc lộ 15 ngập từ 30-70cm, đường sắt Bắc Nam gián đoạn do sạt lở, hơn 4.500 học sinh phải nghỉ học. Dự báo mưa ở Hà Tĩnh còn kéo dài tới ngày 2 tháng 11.",
        },
        {
            "eve": "Chỉ đạo ứng phó thiên tai và khắc phục sự cố đường sắt Bắc Nam",
            "sum": "Ban Chỉ đạo Quốc gia về Phòng chống Thiên tai yêu cầu các tỉnh miền Trung tăng cường ứng phó mưa lũ, trong khi ngành đường sắt đang gấp rút khắc phục sự cố sạt lở, đảm bảo an toàn cho hành khách sau khi tuyến Bắc Nam bị gián đoạn.",
            "ts": ["00:02:05:200", "00:03:08:160"],
            "cnt": "Trước diễn biến phức tạp của tình hình mưa lũ, Ban Chỉ đạo Quốc gia về Phòng chống Thiên tai yêu cầu các tỉnh từ Nghệ An đến Quảng Ngãi theo dõi chặt chẽ dự báo thời tiết, cảnh báo về mưa lớn, ngập lụt, lũ quét, sạt lở đất và thông tin kịp thời đến các cấp chính quyền, người dân để chủ động phòng tránh. Mưa lũ tại Hà Tĩnh đã gây ra nhiều điểm sạt lở, đất đá tràn lên đường ray, khiến tuyến đường sắt Bắc Nam bị chia cắt và buộc phải cấm chạy tàu qua vào rạng sáng ngày 30 tháng 10. Ngay sau sự cố, các đơn vị đã nhanh chóng giải tỏa hành khách, tập trung mọi nguồn lực để khắc phục. Hai chuyến tàu SE1 (từ Hà Nội) và SE20 (từ Đà Nẵng) đã phải dừng hoạt động, ảnh hưởng đến gần 400 hành khách. Ông Trần Anh Tuấn, Phó Tổng Giám đốc Tổng Công ty Đường sắt Việt Nam, cho biết toàn bộ hành khách đã được trung chuyển bằng ô tô để tiếp tục di chuyển theo lịch trình. Tổng Công ty cũng đã chỉ đạo các đơn vị chăm sóc đầy đủ về lương thực, thực phẩm cho hành khách và dự kiến sẽ cho các tàu này di chuyển qua khu vực sự cố trong đêm.",
        },
        {
            "eve": "Tình huống khẩn cấp sạt lở bờ biển tại Bến Tre",
            "sum": "Tỉnh Bến Tre đã công bố tình huống khẩn cấp do sạt lở, xâm thực bờ biển tại huyện Ba Tri, ảnh hưởng nghiêm trọng đến nhiều hộ dân và cơ sở hạ tầng.",
            "ts": ["00:03:08:320", "00:03:45:360"],
            "cnt": "Vào ngày 30 tháng 10, chính quyền tỉnh Bến Tre đã công bố tình huống khẩn cấp về sạt lở, xâm thực bờ biển tại huyện Ba Tri và khẩn trương triển khai các biện pháp ứng phó. Khu vực bị sạt lở, xâm thực nghiêm trọng nhất thuộc địa bàn xã Bảo Thuận, với chiều dài khoảng 4,7 km, ảnh hưởng trực tiếp đến 115 hộ dân, làm hư hại 15 căn nhà. Sạt lở cũng gây hư hỏng hoàn toàn 100 mét đường bê tông, 650 mét bờ bao. Diện tích đất bị ảnh hưởng khoảng 535 héc-ta, trên đất tường phòng hộ ven biển mất 16 héc-ta. Các cơ quan chức năng đang triển khai các biện pháp khẩn cấp để ứng phó và khắc phục hậu quả, bao gồm sơ tán khẩn cấp người và tài sản ra khỏi khu vực nguy hiểm.",
        },
        {
            "eve": "Lễ hội mùa nước nổi và trò chơi đẩy côn bắt cá tại Hậu Giang",
            "sum": "Huyện Phụng Hiệp, Hậu Giang, tổ chức hội thi đẩy côn bắt cá mùa nước nổi, một hoạt động văn hóa kết hợp bảo tồn nghề truyền thống và phát triển du lịch trải nghiệm.",
            "ts": ["00:03:48:560", "00:05:15:280"],
            "cnt": "Khi nước lũ tràn về, người dân đồng bằng sông Cửu Long lại háo hức thu hoạch sản vật mùa nước nổi. Đây cũng là thời điểm các địa phương huyện Phụng Hiệp, tỉnh Hậu Giang tổ chức hội thi đẩy côn bắt cá mùa nước nổi. Hội thi nhằm duy trì và bảo tồn nghề đánh bắt truyền thống, đồng thời tuyên truyền nâng cao ý thức người dân trong việc khai thác nguồn lợi thủy sản đúng quy định. Ông Huỳnh Chí Khải, với gần 20 năm làm nghề, đã được chọn làm đại diện tham gia tranh tài. Côn là dụng cụ được làm từ những cọng sắt nhỏ, gắn vào hai đoạn tre dài, khi người đẩy côn bơi ghe lao về phía trước, thanh cô sắt sẽ chạm vào cá chuối, tạo ra một vùng bong bóng nước, lúc đó chỉ việc lội xuống dùng nơm bắt cá. Huyện Phụng Hiệp mong muốn nâng quy mô hội thi lên cấp huyện, với sự tham gia của tất cả 15 xã, thị trấn để quảng bá hình ảnh đất và người Phụng Hiệp. Trong thời gian tới, huyện sẽ phát triển mô hình này thành một hình thức du lịch trải nghiệm cho du khách khám phá hình thức đánh bắt truyền thống mùa nước nổi.",
        },
        {
            "eve": "Diễn biến phim \"Dâu Bể Mùa Xưa\"",
            "sum": "Bộ phim \"Dâu Bể Mùa Xưa\" bước vào giai đoạn cao trào với những biến cố trong chuyện tình cảm và sức khỏe của các nhân vật chính.",
            "ts": ["00:05:18:240", "00:06:04:480"],
            "cnt": "Những tập tiếp theo của bộ phim \"Dâu Bể Mùa Xưa\" đã đi vào giai đoạn cao trào. Ở tập 11, chuyện tình tay ba giữa hai anh em Hiếu và Nghĩa có bước ngoặt mới khi Bông và Hiếu dần mở lòng cho nhau. Trong khi đó, Nghĩa vẫn ôm mối tương tư, khiến bậc làm cha như ông Bá đau lòng. Một vụ hành hung bất ngờ xảy ra tại tiệm đèn kéo quân của Nghĩa, khiến ông Bá và Nghĩa lo lắng cầu cứu. Cùng lúc đó, bệnh tình của Hiếu có những chuyển biến xấu, còn bà Bá tiếp tục giằng xé giữa hai anh em Hiếu, Nghĩa. Khán giả được mời đón xem những tình tiết hấp dẫn trong tập 11, phát sóng lúc 19 giờ 30 ngày 31 tháng 10 trên kênh HTV7.",
        },
        {
            "eve": "Nam thanh niên dùng rựa truy sát gia đình do tâm thần",
            "sum": "Một vụ án mạng thương tâm xảy ra tại Bình Định khi một nam thanh niên có biểu hiện tâm thần đã dùng rựa sát hại cha và anh trai, làm mẹ bị thương nặng.",
            "ts": ["00:06:06:320", "00:07:12:000"],
            "cnt": "Liên quan đến an ninh trật tự, trong cơn tâm thần, một nam thanh niên ở tỉnh Bình Định đã dùng rựa truy sát ba người trong gia đình, khiến cha và anh ruột tử vong, còn mẹ bị thương rất nặng. Chiều 30 tháng 10, Công an tỉnh Bình Định cho biết đang tạm giữ hình sự đối tượng Hồ Thanh Cường (34 tuổi) để điều tra về hành vi giết người. Khoảng 9 giờ 30 sáng cùng ngày, Cường bất ngờ dùng dao chém vào cha mẹ ruột và anh ruột. Hậu quả, người cha tử vong tại chỗ, anh trai đưa đi cấp cứu tại Trung tâm Y tế thị xã An Nhơn nhưng tử vong trên đường đi. Người mẹ bị thương rất nặng và đang được cấp cứu tại Bệnh viện Đa khoa tỉnh Bình Định. Theo lãnh đạo UBND thị xã An Nhơn, Cường là người bị tâm thần phân liệt, đang điều trị ngoại trú.",
        },
        {
            "eve": "Bắt giữ nhóm trộm cắp mai vàng tại Tây Ninh",
            "sum": "Công an Tây Ninh đã bắt giữ hai đối tượng trong nhóm trộm cây mai vàng trị giá 150 triệu đồng và đang tiếp tục truy tìm các đồng phạm khác.",
            "ts": ["00:07:12:640", "00:08:00:320"],
            "cnt": "Công an thành phố Tây Ninh cho biết đang tạm giữ hình sự ba đối tượng để điều tra về hành vi trộm cắp tài sản và tiêu thụ tài sản do người khác phạm tội mà có. Các đối tượng gồm Huỳnh Thanh Sơn (sinh năm 1993), Nguyễn Trung Hậu (sinh năm 2001) cùng ngụ xã Chà Là và Đỗ Thế Kiệt (sinh năm 1984) ngụ xã Cầu Khởi, huyện Dương Minh Châu. Vào ngày 29 tháng 10, Công an nhận được tin báo của người dân về việc vườn mai bị bốn tên trộm cắt khóa cổng rào đột nhập lấy trộm một cây mai vàng lớn có giá trị 150 triệu đồng. Lực lượng công an đã phối hợp truy bắt được Sơn và Hậu. Các đối tượng khai nhận, Sơn và Hậu cùng hai đối tượng khác đột nhập nhà anh T. để trộm mai, bán được 14 triệu đồng rồi chia nhau tiêu xài. Công an thành phố Tây Ninh đang làm rõ vụ việc và truy bắt các đối tượng còn lại.",
        },
        {
            "eve": "Phát hiện xe khách vận chuyển pháo lậu tại Quảng Nam",
            "sum": "Công an Quảng Nam đã bắt giữ một xe khách vận chuyển số lượng lớn pháo lậu tại huyện Nam Giang.",
            "ts": ["00:08:00:880", "00:08:39:280"],
            "cnt": "Vào ngày 30 tháng 10, Công an tỉnh Quảng Nam cho biết vừa phát hiện và bắt quả tang một ô tô khách 16 chỗ vận chuyển gần 5.000 viên pháo lậu. Vào lúc 23 giờ ngày 29 tháng 10, tại thị trấn Thạnh Mỹ, huyện Nam Giang, lực lượng chức năng đã dừng xe ô tô khách 16 chỗ đang lưu thông theo hướng Kon Tum đi Đà Nẵng. Qua kiểm tra, phát hiện trên xe chở 3 thùng xốp, bên trong có 96 hộp pháo, tổng cộng 4.704 viên. Tại thời điểm kiểm tra, tài xế không xuất trình được giấy tờ chứng minh nguồn gốc số pháo trên. Lực lượng chức năng đã lập biên bản, bàn giao vụ việc cho Công an huyện Nam Giang để tiếp tục điều tra, xử lý.",
        },
        {
            "eve": "Thu giữ hàng tấn thực phẩm đông lạnh hết hạn sử dụng tại Bắc Kạn",
            "sum": "Lực lượng chức năng Bắc Kạn đã phát hiện và thu giữ gần 1,5 tấn thực phẩm đông lạnh hết hạn sử dụng, bốc mùi ôi thiu tại một kho hàng trên địa bàn.",
            "ts": ["00:08:39:600", "00:09:23:040"],
            "cnt": "Gần 1,5 tấn thực phẩm đông lạnh hết hạn sử dụng, bốc mùi ôi thiu vừa bị lực lượng chức năng tỉnh Bắc Kạn phát hiện và thu giữ. Vào ngày 30 tháng 10, khi kiểm tra một kho hàng đông lạnh trên địa bàn phường Sông Cầu, lực lượng chức năng đã phát hiện nhiều sản phẩm đã hết hạn sử dụng, biến màu, ôi thiu, bốc mùi hôi với tổng trọng lượng gần 1,5 tấn. Các sản phẩm bao gồm các loại cá, thịt ba chỉ rút xương, sườn heo, chân giò heo, gà nguyên con, thịt trâu, chân gà nêm chua, xúc xích đông lạnh. Tại thời điểm kiểm tra, chủ kho hàng đông lạnh là ông Phạm Đức Của (sinh năm 1981) không xuất trình được các giấy tờ chứng minh nguồn gốc xuất xứ của các sản phẩm. Tổ công tác đã lập biên bản và đang phối hợp xác minh để xử lý theo quy định của pháp luật.",
        },
        {
            "eve": "Vụ sập giàn giáo tại Hamburg, Đức",
            "sum": "Vụ sập giàn giáo tại công trường xây dựng ở Hamburg, Đức đã khiến ít nhất ba công nhân thiệt mạng, gây khó khăn cho công tác cứu hộ.",
            "ts": ["00:09:41:760", "00:10:31:600"],
            "cnt": "Vào ngày 30 tháng 10, một vụ sập giàn giáo đã xảy ra tại một công trường xây dựng ở thành phố Hamburg, miền bắc nước Đức, làm ít nhất ba công nhân thiệt mạng và nhiều người khác bị chôn vùi dưới đống đổ nát. Theo lực lượng cứu hỏa địa phương, vào thời điểm xảy ra vụ tai nạn, có khoảng 1.300 đến 1.500 công nhân đang làm việc tại công trường. Giàn giáo cao hơn mặt đất khoảng tám tầng. Trước khi đổ sập, công trường xây dựng đã được sơ tán. Lực lượng cứu hỏa cho biết nỗ lực cứu hộ gặp nhiều khó khăn. Nhà chức trách ban đầu thông báo có năm người thiệt mạng, nhưng sau đó đã báo cáo lại là ba người. Vụ tai nạn xảy ra tại khu dân cư ở quận HafenCity, thuộc thành phố cảng Hamburg, trên sông Elbe, nơi đang được tái phát triển với nhiều tòa nhà chung cư, văn phòng, khách sạn và cửa hàng.",
        },
        {
            "eve": "Phim hoạt hình kể câu chuyện con tin trong xung đột Israel-Hamas",
            "sum": "Một bà mẹ có con bị Hamas bắt cóc đã tạo phim hoạt hình để chia sẻ câu chuyện đau buồn của mình, đồng thời hy vọng vào sự đoàn tụ.",
            "ts": ["00:10:32:160", "00:12:03:440"],
            "cnt": "Cuộc xung đột giữa lực lượng Hamas kiểm soát Dải Gaza và Israel đã leo thang khi quân đội Israel mở rộng chiến dịch trên bộ tại Gaza. Trước đó, ngày 7 tháng 10, Hamas đã bất ngờ đột kích tấn công vào các thành phố, thị trấn của Israel, giết chết nhiều người và bắt giữ con tin. Một bà mẹ có hai con trai bị Hamas bắt cóc đã làm một phim hoạt hình để kể về câu chuyện đau buồn của mình. Câu chuyện về Jadin (12 tuổi) và Om (16 tuổi), hai anh em bị bắt cóc tại khu vực Nir Oz, miền nam Israel, khi ở nhà một mình. Mẹ của hai đứa trẻ là người kể chuyện trong đoạn phim hoạt hình này. Đạo diễn hoạt hình Yoni Goodman, nổi tiếng tại Israel với bộ phim \"When the Elephants Come\", đã thực hiện đoạn phim sau khi trò chuyện với bà Renan Gom để lắng nghe câu chuyện của bà. Bà mẹ chia sẻ rằng bà liên tục gặp ác mộng và mong muốn đưa câu chuyện này ra khỏi đầu trẻ em, nhấn mạnh trẻ em không phải là con bài mặc cả. Bà tin rằng con mình vẫn còn sống khi hai con tin lớn tuổi người Israel được Hamas thả tự do nói với bà rằng họ đã nghe thấy tiếng trẻ con khi bị bắt giữ ở Gaza.",
        },
        {
            "eve": "Sông băng ở Nepal tan chảy với tốc độ kỷ lục",
            "sum": "Tổng Thư ký Liên Hợp Quốc cảnh báo sông băng ở Nepal đang tan chảy với tốc độ kỷ lục, đe dọa nguồn nước và cuộc sống của hàng tỷ người do biến đổi khí hậu.",
            "ts": ["00:12:03:440", "00:13:07:120"],
            "cnt": "Các sông băng ở Nepal đang tan chảy với tốc độ kỷ lục và tình hình ngày càng nghiêm trọng. Đây là phát biểu của Tổng Thư ký Liên Hợp Quốc António Guterres đưa ra vào ngày 29 tháng 10, trong khuôn khổ chuyến thăm chính thức Nepal. Phát biểu trước báo giới tại Kathmandu, Tổng Thư ký Liên Hợp Quốc cho biết sẽ đến thăm dãy Himalaya để tận mắt chứng kiến tác động khủng khiếp của biến đổi khí hậu đối với các sông băng. Ông nhấn mạnh tình hình rất nghiêm trọng và ngày càng gia tăng, Nepal đã mất gần một phần ba diện tích sông băng chỉ sau hơn 30 năm, và sông băng tan chảy với tốc độ kỷ lục. Tác động với cộng đồng là thảm khốc, và ông sẽ gặp cư dân địa phương trên dãy Himalaya để lắng nghe về việc họ bị ảnh hưởng như thế nào. Theo các nhà khoa học, các sông băng ở dãy Himalaya, nguồn cung cấp nước quan trọng cho gần hai tỷ người trên thế giới, đã tan chảy nhanh hơn bao giờ hết. Chúng có thể mất tới 75% thể tích vào cuối thế kỷ do hiện tượng ấm lên toàn cầu, đe dọa đời sống cộng đồng với những thảm họa khó lường và nguy cơ gây thiệt hại nghiêm trọng.",
        },
        {
            "eve": "Chương trình cung cấp bữa ăn giá thấp cho học sinh tại Kenya",
            "sum": "Tổ chức \"Piec for Education\" tại Kenya đã cung cấp hơn 29 triệu bữa ăn giá thấp cho học sinh, giúp cải thiện tình trạng dinh dưỡng và học tập của các em.",
            "ts": ["00:13:07:920", "00:14:18:720"],
            "cnt": "Tại Kenya, tổ chức phi chính phủ \"Piec for Education\" đang cung cấp khoảng 165.000 bữa ăn với giá thấp cho học sinh mỗi ngày. Đây là một phần của dự án lớn nhằm cung cấp bữa ăn cho khoảng 4 triệu học sinh tiểu học và hàng triệu học sinh các cấp khác tại quốc gia châu Phi này. Đây là chương trình mang bữa ăn giá thấp cho học sinh lớn nhất từ trước đến nay ở Kenya. Chính quyền địa phương cũng hỗ trợ một phần chi phí cho các bữa ăn. Kể từ khi hoạt động, chương trình đã cung cấp hơn 29 triệu bữa ăn học đường. Tùy theo mức trợ cấp của địa phương, phụ huynh sẽ trả từ 50% đến 83% chi phí bữa ăn, mỗi bữa ăn có giá 30 Shilling Kenya (khoảng 0,2 đô la Mỹ). Tuy nhiên, tình trạng lạm phát, nghèo đói kéo dài khiến nhiều gia đình không thể lo nổi việc ăn uống cho con cái. Trước đây, học sinh phải mang đồ ăn từ nhà theo, khi đến giờ ăn thức ăn đã nguội lạnh, nhiều bạn còn không đến lớp và không tập trung học do bị đói. Giờ đây, các em đã có bữa ăn nóng và thơm ngon, giúp việc học tập tốt hơn. Nhờ những kết quả tích cực, dự án đã được phụ huynh, học sinh và các trường học ở Kenya đón nhận và kỳ vọng sẽ tiếp tục mở rộng trong thời gian tới.",
        },
        {
            "eve": "Giải vô địch thế giới Phô mai Raclette đầu tiên tại Thụy Sĩ",
            "sum": "Thụy Sĩ đã đăng cai thành công Giải vô địch thế giới Phô mai Raclette đầu tiên, với các sản phẩm phô mai chất lượng cao và phần lớn giải thưởng thuộc về nước chủ nhà.",
            "ts": ["00:14:19:200", "00:15:33:520"],
            "cnt": "Cuối tuần qua, giải vô địch thế giới Phô mai Raclette đầu tiên đã diễn ra tại Thụy Sĩ, với chiến thắng gần như tuyệt đối thuộc về chủ nhà. Mùi phô mai tan chảy nồng nàn bao trùm một góc nhỏ trên hồ Geneva, Thụy Sĩ. Phô mai Raclette ra đời vài thế kỷ trước, khi những người chăn cừu hâm nóng phô mai gần bếp lửa rồi cạo phần tan chảy đi ăn. Đây là một trong những biểu tượng của đất nước Thụy Sĩ. Vào ngày 29 tháng 10, các nhà sản xuất, chuyên gia, về phô mai, chủ nhà hàng đã cùng có mặt tại bang Valais để tìm Raclette ngon nhất thế giới. Có 90 bánh phô mai và 90 loại Raclette được mang ra thi đấu. Raclette ngon phải giàu kem, mịn màng, hình thức, màu sắc, kết cấu đẹp, không dai, không như kẹo, không chảy dầu, chất béo không được chảy ra trên đĩa, và về mặt hương vị phải thuần túy, không lai, không đắng. Phần lớn người dự thi đến từ Thụy Sĩ hoặc Pháp, Bỉ, Canada, Italia và Romania. Năm nay, chủ nhà Thụy Sĩ đã giành hầu hết giải thưởng, chỉ chừa một giải nhì cho người Pháp.",
        },
        {
            "eve": "Vở ballet \"Thằng Gù Nhà Thờ Đức Bà\" phiên bản Trung Quốc",
            "sum": "Vở ballet \"Thằng Gù Nhà Thờ Đức Bà\" phiên bản Trung Quốc đã ra mắt thành công, kết hợp tinh hoa nghệ thuật phương Đông và phương Tây, chuẩn bị cho tour diễn quốc tế.",
            "ts": ["00:15:34:560", "00:16:38:880"],
            "cnt": "Vở ballet \"Thằng Gù Nhà Thờ Đức Bà\" phiên bản Trung Quốc vừa ra mắt khán giả nước này tại Nhà hát Liêu Ninh. Tác phẩm kết hợp nét đẹp của ballet phương Đông nhưng vẫn giữ nguyên cốt truyện của phương Tây. Đội ngũ sáng tạo vở ballet đã tập hợp nghệ sĩ Trung Quốc, Đức, Pháp và nhiều quốc gia khác nhằm tôn vinh sự đa dạng. Tác phẩm do Đoàn Múa Ballet Liêu Ninh thực hiện với sự hỗ trợ của biên đạo múa nổi tiếng thế giới Bà Jiří Kylián. Bà nhấn mạnh rằng Quasimodo không phải là một con quái vật mà có một trái tim nhân hậu, vì thế việc thể hiện nhân cách tốt bụng của Quasimodo là điều bà rất chú trọng. Vở ballet kết hợp chủ nghĩa hiện thực và trừu tượng, sân khấu được lấy cảm hứng từ những bức tranh sơn dầu của Pháp, với âm nhạc kết hợp hài hòa giữa các thể loại cổ điển và đương đại. Sau lần công diễn tại thành phố Thẩm Dương, tỉnh Liêu Ninh, vở ballet \"Thằng Gù Nhà Thờ Đức Bà\" sẽ được trình diễn tại Trung tâm Nghệ thuật ở Bắc Kinh vào tháng 12 tới, trước khi bắt đầu chuyến lưu diễn châu Âu vào năm sau.",
        },
        {
            "eve": "FIFA cấm cựu Chủ tịch Liên đoàn Bóng đá Tây Ban Nha 3 năm",
            "sum": "FIFA đã cấm cựu Chủ tịch Liên đoàn Bóng đá Tây Ban Nha, Luis Rubiales, tham gia mọi hoạt động bóng đá trong ba năm vì hành vi hôn nữ cầu thủ Jenni Hermoso.",
            "ts": ["00:16:39:440", "00:17:39:280"],
            "cnt": "Vào ngày 30 tháng 10, Liên đoàn Bóng đá Thế giới (FIFA) đã cấm cựu Chủ tịch Liên đoàn Bóng đá Tây Ban Nha, Luis Rubiales, tham gia mọi hoạt động bóng đá trong ba năm, liên quan đến hành vi sai trái của ông trong trận chung kết World Cup Nữ 2023. Theo Ủy ban Kỷ luật của FIFA, ông Rubiales đã vi phạm Điều 13 trong Quy tắc Kỷ luật FIFA liên quan đến vụ việc diễn ra trong trận chung kết World Cup Nữ ngày 20 tháng 8 năm 2023. Cũng theo FIFA, ông Rubiales có quyền kháng cáo. Ông Rubiales đã hôn tiền đạo Jenni Hermoso trên lễ trao giải sau khi đội tuyển Tây Ban Nha đăng quang World Cup Nữ. Ông khẳng định nụ hôn này có sự đồng thuận giữa hai bên, nhưng Hermoso lại nói rằng cô đã không đồng ý. Sức ép gia tăng từ nhiều phía đã khiến ông Rubiales từ chức Chủ tịch Liên đoàn Bóng đá Tây Ban Nha. Trong khi đó, Hermoso đã trở lại thi đấu cho tuyển nữ Tây Ban Nha. Mới đây, cô đã ghi bàn thắng duy nhất giúp tuyển nữ Tây Ban Nha giành chiến thắng 1-0 trước Italia tại giải \"Millennium Series\" vào ngày 27 tháng 10.",

        },
        {
            "eve": "Cuộc đua thuyền Transat Jacques Vabre bị ảnh hưởng bởi thời tiết xấu",
            "sum": "Cuộc đua thuyền Jacques Vabre khởi hành tại Pháp đã bị ảnh hưởng nặng nề bởi thời tiết xấu, buộc gần một nửa số thuyền phải hoãn hoặc bỏ cuộc.",
            "ts": ["00:17:39:280", "00:18:44:960"],
            "cnt": "Vào ngày 29 tháng 10, cuộc đua thuyền tranh giải Jacques Vabre lần thứ 16 đã khởi hành ngoài khơi Le Havre của Pháp. Tuy nhiên, vùng nước động mạnh đã khiến một nửa số thuyền tham gia phải ở lại cảng. Cuộc đua Transat Jacques Vabre là cuộc đua du thuyền đi theo tuyến đường giao thương cà phê lịch sử Pháp và Brazil, ra đời năm 1993 và diễn ra hai năm một lần vào những năm lẻ. Sự kiện được đặt theo tên một thương hiệu cà phê của Pháp đồng thời là nhà tài trợ. Đây là cuộc đua dành cho hai người, đi từ Le Havre đến Salvador de Bahia, Brazil. Các phương tiện bao gồm tàu nhiều thân và tàu một thân thuộc các hạng UIM TIM, tàu đa thân dài 70-105 feet, MOD70, Class40. Tất cả các loại thiết bị hỗ trợ điều hướng đều được phép sử dụng, ngoại trừ Class40. Ngày diễn ra cuộc đua, điều kiện thời tiết xấu đi quá nhanh, sóng dồi cao cùng gió giật đã khiến ba tổ chức phải hoãn việc khởi hành của gần một nửa đội tàu, và bỏ cuộc giữa chừng.",
        },
        {
            "eve": "Cập nhật xung đột Israel-Hamas và phản ứng quốc tế",
            "sum": "Xung đột tại Gaza tiếp diễn, Mỹ kêu gọi tạm ngừng giao tranh để viện trợ, trong khi Nga cáo buộc Ukraine liên quan vụ người biểu tình tấn công sân bay ở Dagestan.",
            "ts": ["00:18:46:000", "00:20:47:920"],
            "cnt": "Các cuộc tấn công bằng tên lửa vẫn tiếp tục diễn ra trong đêm qua tại Dải Gaza, chiếu sáng bầu trời miền nam Israel trong bối cảnh lực lượng mặt đất của Israel đã tiến sâu hơn vào khu vực này. Lực lượng Phòng vệ Israel (IDF) cho biết các tên lửa phóng từ Dải Gaza đã bị hệ thống phòng không Iron Dome của nước này đánh chặn. Thiệt hại đã xảy ra ở Ashdod, nhưng chưa có thương vong nào được báo cáo. Trong khi đó, Nhà Trắng cho biết không ủng hộ những lời kêu gọi ngừng bắn vào thời điểm này, mà thay vào đó nên xem xét việc tạm ngừng giao tranh để tạo điều kiện cho viện trợ vào Gaza. Theo người phát ngôn Hội đồng An ninh Quốc gia Mỹ, John Kirby, dự kiến số lượng xe tải viện trợ vào Gaza qua cửa khẩu Rafah ở Ai Cập sẽ tăng lên khoảng 100 xe mỗi ngày.\n\nVào ngày 30 tháng 10, người phát ngôn Văn phòng Tổng thống Nga, Dmitry Peskov, cho biết vụ việc người biểu tình phản đối Israel xông vào sân bay Makhachkala thuộc vùng Dagestan có yếu tố tác động từ bên ngoài. Ông Peskov nói rằng sự cố xảy ra tại sân bay Makhachkala phần lớn là do tác động từ bên ngoài, bao gồm cả tác động thông tin. Trong khi đó, người phát ngôn Bộ Ngoại giao Nga Maria Zakharova cáo buộc Ukraine đóng vai trò trực tiếp và chủ chốt liên quan tới vụ người biểu tình tràn vào sân bay Makhachkala. Phản ứng trước tuyên bố của bà Zakharova, phía Ukraine khẳng định Kiev không liên quan tới vụ việc tại sân bay ở vùng Dagestan. Sân bay Makhachkala dự kiến mở cửa trở lại vào ngày 31 tháng 10, thay vì ngày 6 tháng 11 như thông báo trước đó. Vào ngày 29 tháng 10, hàng trăm người đã tụ tập tại sân bay Makhachkala biểu tình phản đối cuộc xung đột Hamas-Israel. Họ đã xông vào bên trong sân bay và khu vực đường băng sau khi chuyến bay theo lịch trình từ Tel Aviv hạ cánh. Cảnh sát đã được huy động đến hiện trường để giải tán đám đông. Hơn 20 người, bao gồm cảnh sát và dân thường, đã bị thương. Bộ Nội vụ Nga đã xác định danh tính của 150 người tham gia biểu tình, bắt giữ được 60 người và đang truy tìm những người bỏ trốn.",
        }
    ]
    ```    
    """
]